- hosts: webserver
  tags: ['webserver']
  become: yes
  tasks:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: wait for nginx to restart
      pause:
        seconds: 15

    - name: restart redis
      service: name=redis-server state=restarted

    - name: stop previous forever process
      shell: forever stopall

    - name: run server
      shell: forever start server.js  chdir=/root/production-www/server-side/site

    - name: run patient
      shell: forever start patient.js  chdir=/root/production-www/special

